version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home

  tomcat:
    image: tomcat:latest
    ports:
      - 8080:8080
    container_name: tomcat
    volumes:
      - ~/webapp:/usr/local/tomcat/webapps/webapp

